### ISSUE TITLE
Installing node-linq throws error

### ISSUE THREAD

**Issue by KamalVora** [yocontra/node-linq#11]
I am unable to install node-linq used in our source code. It was installing properly until now. Because of this error we are not able to deploy code to production as installations on production are failing. Error is due to coffee-script which node-linq is using internally. I have attached the screenshot of error. Please Help.

![node-linqinstallfail](https://user-images.githubusercontent.com/34127957/33429253-14c3707e-d5f2-11e7-9633-fa3d06c4be8f.png)

**Comment by rovase** [comment]
Facing the same issue. Looks like an issue with coffee script.
https://github.com/jashkenas/coffeescript/issues/4805

**Comment by contra** [comment]
The versions of coffee-script are pinned but apparently coffee-script force published this crap over existing versions? I'll look into it right now.

**Comment by yocontra** [comment]
Downstream coffee-script issue - you can edit your package-lock to change the coffee-script version to the one in that issue to fix it temporarily. Sorry for the inconvenience, but not really much I can do - they published a broken package as a patch release so everyone is facing it atm.

https://github.com/jashkenas/coffeescript/issues/4805

Should be fixed soon, looks like they have a fire under their ass on that ticket ^

After they publish a fix just `npm update` to grab it.

**Comment by KamalVora** [comment]
I have created a pull request to specific version of coffee-script.
