### ISSUE TITLE
No examples in javascript

### ISSUE THREAD

**Issue by awlawl** [yocontra/node-linq#2]
I've loved using this package but since I am not a coffeescript dev, it took me some extra research to get things running in javascript. I am willing to contribute examples to the readme but I had some questions first:
1. I translated the examples from the readme into javascript and them made them into mocha tests so that I was sure they really worked. The caveat here is that I had to remove the use of the file date sorting and extension filtering so that the tests could be deterministic. Instead I sort alphabetically and filter on the end of the filename. To be clear, I imagine that you would want to coffeescript tests to use the same syntax. Is this ok?
2. Can I submit in two parts, sync only versions first? I am having problems getting the async versions to work.

**Comment by yocontra** [comment]
Yep sounds good to me
